name: Laravel Pint

on:
  push:
    branches:
      - main

jobs:
  laravel-pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:

          php-version: '8.4'
          tools: composer:v2

      - name: Install Laravel Pint
        run: composer global require laravel/pint

      - name: Run Pint
        run: pint

      - name: Push Changes Back to Repo
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "musahmusah"
          git config --global user.email "shehialiyu0@gmail.com"
          
          # Explicitly authenticate using GH_PAT
          git remote set-url origin https://musahmusah:${GH_PAT}@github.com/MusahMusah/wcag_checker.git
          
          # Check if there are any changes
          git diff --quiet && exit 0
          
          git add .
          git commit -m "Laravel Pint formatting" || exit 0
          git push origin main